name: bus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  intl: ^0.18.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  iconsax: ^0.0.8
  google_nav_bar: ^5.0.7
  dio: ^5.9.0
  supabase: ^2.8.0
  get_it: ^8.2.0
  auto_route: ^10.1.0+1
  get: ^4.7.2
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  uuid: ^4.5.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4

flutter:
  assets:
    - image/images/
    - image/logos/
    - image/svg/

  uses-material-design: true
  
  